# Generated by Django 5.2.3 on 2025-07-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='webcms')),
                ('email', models.CharField(max_length=33)),
                ('name', models.CharField(max_length=33)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phrase', models.CharField(max_length=500)),
            ],
        ),
    ]
