# Generated by Django 5.0.4 on 2024-09-14 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='form',
        ),
    ]
