# Generated by Django 5.1.4 on 2025-04-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0002_test_duration_testsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
