# Generated by Django 5.1.4 on 2025-04-06 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0001_initial'),
        ('tester', '0004_subject_question_form_questionbank_question_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticator.form'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tester.subject'),
        ),
    ]
